#!/usr/bin/env python3

import sys
import os

def sh(x): return max(-32768, min(32767, int(round(x))))

if len(sys.argv) != 2:
	sys.stderr.write("usage: %s <obj>\n" % sys.argv[0])
	sys.exit(1)
fn = sys.argv[1]
with open(fn, "r") as f:
	vtx = []
	obj = []
	tri = None
	mtl = "0"
	for line in f:
		arg = line.split()
		if not arg: continue
		elif arg[0] == "v":
			vtx.append(tuple([sh(float(x)) for x in arg[1:4]]))
		elif arg[0] == "f":
			if tri is None:
				for i, tri in obj:
					if i == mtl: break
				else:
					tri = []
					obj.append((mtl, tri))
			face = [int(v.partition("/")[0])-1 for v in arg[1:]]
			for i in range(len(face)-2):
				tri.append((face[0], face[i+1], face[i+2]))
		elif arg[0] == "usemtl":
			mtl = arg[1]
			tri = None
print("M_VTX, %d," % len(vtx))
for v in vtx: print("%d, %d, %d," % v)
for mtl, tri in obj:
	print("%s, %d," % (mtl, len(tri)))
	for t in tri: print("%d, %d, %d," % t)
print("M_PLANEEND,")
