#ifndef __SM64_DEFOBJLANG_H__
#define __SM64_DEFOBJLANG_H__

#define OBJ_CMD_INIT            0
#define OBJ_CMD_SLEEP           1
#define OBJ_CMD_CALL            2
#define OBJ_CMD_RETURN          3
#define OBJ_CMD_JUMP            4
#define OBJ_CMD_FOR             5
#define OBJ_CMD_FEND            6
#define OBJ_CMD_FCONTINUE       7
#define OBJ_CMD_WHILE           8
#define OBJ_CMD_WEND            9
#define OBJ_CMD_EXIT            10
#define OBJ_CMD_END             11
#define OBJ_CMD_CALLBACK        12
#define OBJ_CMD_ADDF            13
#define OBJ_CMD_SETF            14
#define OBJ_CMD_ADDI            15
#define OBJ_CMD_SETI            16
#define OBJ_CMD_SETFLAG         17
#define OBJ_CMD_CLRFLAG         18
#define OBJ_CMD_SETRANDA        19
#define OBJ_CMD_SETRANDF        20
#define OBJ_CMD_SETRANDI        21
#define OBJ_CMD_ADDRANDF        22
#define OBJ_CMD_ADDRANDA        23
#define OBJ_CMD_24              24
#define OBJ_CMD_25              25
#define OBJ_CMD_26              26
#define OBJ_CMD_SETSHAPE        27
#define OBJ_CMD_MAKEOBJ         28
#define OBJ_CMD_DESTROY         29
#define OBJ_CMD_GROUND          30
#define OBJ_CMD_ADDFW           31
#define OBJ_CMD_ADDIW           32
#define OBJ_CMD_BILLBOARD       33
#define OBJ_CMD_HIDE            34
#define OBJ_CMD_SETHITBOX       35
#define OBJ_CMD_36              36
#define OBJ_CMD_SLEEPW          37
#define OBJ_CMD_FOR2            38
#define OBJ_CMD_SETPTR          39
#define OBJ_CMD_SETANIME        40
#define OBJ_CMD_MAKEOBJCODE     41
#define OBJ_CMD_SETMAP          42
#define OBJ_CMD_SETHITBOXOFF    43
#define OBJ_CMD_MAKECHILD       44
#define OBJ_CMD_SAVEPOS         45
#define OBJ_CMD_SETDMGBOX       46
#define OBJ_CMD_SETHITTYPE      47
#define OBJ_CMD_SETPHYSICS      48
#define OBJ_CMD_SETHITFLAG      49
#define OBJ_CMD_SETSCALE        50
#define OBJ_CMD_CLRPARENTFLAGW  51
#define OBJ_CMD_INC             52
#define OBJ_CMD_CLRACTIVE       53
#define OBJ_CMD_SETS            54
#define OBJ_CMD_MAKESPLASH      55

#endif /* __SM64_DEFOBJLANG_H__ */
