#ifndef __SM64_DEFPRGLANG_H__
#define __SM64_DEFPRGLANG_H__

#define PRG_CMP_AND             0
#define PRG_CMP_NAND            1
#define PRG_CMP_EQ              2
#define PRG_CMP_NE              3
#define PRG_CMP_LT              4
#define PRG_CMP_LE              5
#define PRG_CMP_GT              6
#define PRG_CMP_GE              7

#define PRG_VAR_FILE            0
#define PRG_VAR_COURSE          1
#define PRG_VAR_LEVEL           2
#define PRG_VAR_STAGE           3
#define PRG_VAR_SCENE           4

#define PRG_CMD_EXECUTE          0
#define PRG_CMD_CHAIN            1
#define PRG_CMD_EXIT             2
#define PRG_CMD_SLEEP            3
#define PRG_CMD_FREEZE           4
#define PRG_CMD_JUMP             5
#define PRG_CMD_CALL             6
#define PRG_CMD_RETURN           7
#define PRG_CMD_FOR              8
#define PRG_CMD_DONE             9
#define PRG_CMD_REPEAT           10
#define PRG_CMD_UNTIL            11
#define PRG_CMD_JUMPIF           12
#define PRG_CMD_CALLIF           13
#define PRG_CMD_IF               14
#define PRG_CMD_ELSE             15
#define PRG_CMD_ENDIF            16
#define PRG_CMD_CALLBACK         17
#define PRG_CMD_PROCESS          18
#define PRG_CMD_SET              19
#define PRG_CMD_PUSH             20
#define PRG_CMD_PULL             21
#define PRG_CMD_LOADCODE         22
#define PRG_CMD_LOADDATA         23
#define PRG_CMD_LOADPRES         24
#define PRG_CMD_LOADFACE         25
#define PRG_CMD_LOADTEXT         26
#define PRG_CMD_STAGEINIT        27
#define PRG_CMD_STAGEEXIT        28
#define PRG_CMD_STAGESTART       29
#define PRG_CMD_STAGEEND         30
#define PRG_CMD_SCENESTART       31
#define PRG_CMD_SCENEEND         32
#define PRG_CMD_SHAPEGFX         33
#define PRG_CMD_SHAPE            34
#define PRG_CMD_SHAPESCALE       35
#define PRG_CMD_OBJECT           36
#define PRG_CMD_PLAYER           37
#define PRG_CMD_PORT             38
#define PRG_CMD_BGPORT           39
#define PRG_CMD_CONNECT          40
#define PRG_CMD_SCENEOPEN        41
#define PRG_CMD_SCENECLOSE       42
#define PRG_CMD_PLAYEROPEN       43
#define PRG_CMD_PLAYERCLOSE      44
#define PRG_CMD_SCENEPROC        45
#define PRG_CMD_MAP              46
#define PRG_CMD_AREA             47
#define PRG_CMD_MESSAGE          48
#define PRG_CMD_ENV              49
#define PRG_CMD_50               50
#define PRG_CMD_WIPE             51
#define PRG_CMD_VIBLACK          52
#define PRG_CMD_VIGAMMA          53
#define PRG_CMD_BGM              54
#define PRG_CMD_PLAYBGM          55
#define PRG_CMD_AUDFADEOUT       56
#define PRG_CMD_TAG              57
#define PRG_CMD_58               58
#define PRG_CMD_JET              59
#define PRG_CMD_VAR              60

#endif /* __SM64_DEFPRGLANG_H__ */
